spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysql?characterEncoding=utf8&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: root
