server:
  port: 8081
  servlet:
    context-path: /demo
    session:
      cookie:
        path: /
        http-only: false


mybatis:

  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.learn.demo.mapper


spring:
  profiles:
    active: true

excludeUrl: /**/*.js,/**/*.css,/**/*.html,/demo/user/login