spring:
  datasource:
    url: jdbc:mysql://49.233.146.62:3306/mysql?characterEncoding=utf8&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 103145
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 49.233.146.62
    port: 6379
    password: 103145
