spring:
  datasource:
    url: jdbc:mysql://zengqingquan.xyz:3306/zqq?characterEncoding=utf8&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 103145
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: root
